name: Build Clearlinux kernel DEB package

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        description: Release type
        options:
          - none
          - pre-release
          - release

env:
  HOME: /home/runner
  KERNEL_STABLE_VER: 6.7.5
  PKGVER: 1

jobs:
    build:
      runs-on: self-hosted
      steps:
        - uses: actions/checkout@v4
        - name: Download linux kernel ${{ env.KERNEL_STABLE_VER }} source
          run: |
            wget https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${{ env.KERNEL_STABLE_VER }}.tar.xz \
              && tar xvf linux-${{ env.KERNEL_STABLE_VER }}.tar.xz

        - name: Setup dependencies
          run: |
            sudo apt-get update \
            && sudo apt-get install -y build-essential \
                 bc kmod cpio flex libncurses-dev \
                 libelf-dev libssl-dev dwarves bison \
                 gawk openssl libssl-dev dkms libudev-dev \
                 libpci-dev libiberty-dev autoconf \
                 debhelper lz4

        - name: Apply patch
          working-directory: linux-${{ env.KERNEL_STABLE_VER }}
          run: |
            git config user.name "GitHub Actions"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git clone https://github.com/clearlinux-pkgs/linux.git ../clear-patches \
             && for i in $(grep '^Patch' ../clear-patches/linux.spec |\
                  grep -Ev '^Patch0132|^Patch0118|^Patch0113|^Patch0138|^Patch0139' | sed -n 's/.*: //p'); do
                    patch -Np1 -i "../clear-patches/${i}"
                done

        - name: Copy .config and setup some config
          working-directory: linux-${{ env.KERNEL_STABLE_VER }}
          run: |
            cp ../config .config
            scripts/config --set-str DEFAULT_HOSTNAME "debian" \
                           -e IKCONFIG \
                           -e IKCONFIG_PROC
            scripts/config --set-str LOCALVERSION "-clear"
            scripts/config -m NTFS3_FS \
                           -e NTFS3_LZX_XPRESS \
                           -e NTFS3_FS_POSIX_ACL
            scripts/config -m SMB_SERVER \
                           -e SMB_SERVER_SMBDIRECT \
                           -e SMB_SERVER_CHECK_CAP_NET_ADMIN \
                           -e SMB_SERVER_KERBEROS5
            scripts/config -e SECURITY_SELINUX \
                           -e SECURITY_SELINUX_BOOTPARAM \
                           -e SECURITY_SMACK \
                           -e SECURITY_SMACK_BRINGUP \
                           -e SECURITY_SMACK_NETFILTER \
                           -e SECURITY_SMACK_APPEND_SIGNALS \
                           -e SECURITY_TOMOYO \
                           -e SECURITY_APPARMOR \
                           -e SECURITY_YAMA
            scripts/config -e DEBUG_INFO_NONE \
                           -d DEBUG_INFO_DWARF_TOOLCHAIN_DEFAULT \
                           -d DEBUG_INFO_DWARF4 \
                           -d DEBUG_INFO_DWARF5

        - name: Build
          working-directory: linux-${{ env.KERNEL_STABLE_VER }}
          env:
            KDEB_COMPRESS: "xz"
          run: |
            make olddefconfig
            make \
              KDEB_PKGVERSION=$(make kernelversion)-${{ env.PKGVER }} \
              -j`nproc` \
              bindeb-pkg
        
        - name: Upload config
          uses: actions/upload-artifact@v3
          with:
            name: config
            path: linux-${{ env.KERNEL_STABLE_VER }}/.config
        
        - name: Upload deb
          uses: actions/upload-artifact@v3
          with:
            name: deb
            path: linux-*.deb
        
        - name: Release
          if: ${{ github.event.inputs.release != 'none' }}
          uses: ncipollo/release-action@v1
          with:
            artifacts: linux-*.deb
            prerelease: ${{ github.event.inputs.release == 'pre-release' }}
            makeLatest: ${{ github.event.inputs.release == 'release' }}
            tag: ${{ env.KERNEL_STABLE_VER }}-${{ env.PKGVER }}

